site_name: Cartodruid
site_url: https://docs.cartodruid.es
theme:
  name: material
  logo: img/ic_launcher.png
  favicon: img/ic_launcher_2.png
  palette:
    scheme: default
    primary: brown
  custom_dir: overrides
  features:
    - content-title-meta

plugins:
  - include-markdown
  - search
  - i18n:
      default_language: 'en'
      languages:
        en: "English"
        es: "Español"

nav:
  - 1 Introduction: index.md
  - 1 Introducción: index.es.md
  - 2 Application file structure: fileStructure/estructura_ficheros.md
  - 2 Estructura de ficheros de la aplicación: fileStructure/estructura_ficheros.es.md
  - 3 Creating layers from Cartodruid: layer/capas.md
  - 3 Creación de capas desde CartoDruid: layer/capas.es.md
  - 4 Project management with CRTDRD: project/proyectos.md
  - 4 Gestión de proyectos con CRTDRD: project/proyectos.es.md
  - 5 Layer configuration in projects: layerConfig/configuracion_capas.md
  - 5 Configuración de capas en proyectos: layerConfig/configuracion_capas.es.md
  - 6 Symbolization configuration in projects: symbology/simbologias.md
  - 6 Configuración de simbologías en proyectos: symbology/simbologias.es.md
  - 7 Configuration of form display: form/formularios.md
  - 7 Configuración de la visualización de formularios: form/formularios.es.md
  - 8 Practical cases of vector layer parameterization: cases/casos_practicos.md
  - 8 Casos prácticos de parametrización de capas vectoriales: cases/casos_practicos.es.md
  - 9 SQLite-Spatialite layers in CartoDruid: sqliteLayers/sqllayers.md
  - 9 Capas SQLite-Spatialite en CartoDruid: sqliteLayers/sqllayers.es.md

 
extra:
  alternate:
    - name: English
      link: ""
      lang: en
    - name: Español
      link: /index/index.es/
      lang: es

extra_css:
  - css/extra.css

extra_javascript:
  - js/extra.js
  - js/analytics.js

markdown_extensions:
  - attr_list





